id: IE7E3EC47
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T14:27:49+00:00'
last_modified: '2022-06-08T13:41:51.601867+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN509
  title: བརྒྱད་སྟོང་སུམ་བིད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B043:
      image_group_id: I3CN4554
      title: ''
      total_pages: 1108
      order: 1
      base_file: B043.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
