id: P010450
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN509
  title: བརྒྱད་སྟོང་སུམ་བིད།
  author: ''
  volumes:
    42db63923c404db4b8b138a0c44ac71c:
      image_group_id: I3CN4554
      title: ''
      volume_number: 1
      total_pages: 1108
      base_file: v001.txt
